[2025-04-24T21:15:43.828+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TATASTEEL.NS manual__2025-04-24T21:15:40.505356+00:00 [queued]>
[2025-04-24T21:15:43.839+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TATASTEEL.NS manual__2025-04-24T21:15:40.505356+00:00 [queued]>
[2025-04-24T21:15:43.840+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-24T21:15:43.855+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): branch_TATASTEEL.NS> on 2025-04-24 21:15:40.505356+00:00
[2025-04-24T21:15:43.867+0000] {standard_task_runner.py:60} INFO - Started process 4205 to run task
[2025-04-24T21:15:43.873+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'raw_prices_data_downloader_branching', 'branch_TATASTEEL.NS', 'manual__2025-04-24T21:15:40.505356+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/raw_price_data_testing.py', '--cfg-path', '/tmp/tmph46lihgb']
[2025-04-24T21:15:43.875+0000] {standard_task_runner.py:88} INFO - Job 227: Subtask branch_TATASTEEL.NS
[2025-04-24T21:15:43.939+0000] {task_command.py:423} INFO - Running <TaskInstance: raw_prices_data_downloader_branching.branch_TATASTEEL.NS manual__2025-04-24T21:15:40.505356+00:00 [running]> on host 8291240c5d79
[2025-04-24T21:15:44.041+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_prices_data_downloader_branching' AIRFLOW_CTX_TASK_ID='branch_TATASTEEL.NS' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T21:15:40.505356+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T21:15:40.505356+00:00'
[2025-04-24T21:15:44.043+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: prices_pipeline.<locals>.branch_condition() missing 1 required positional argument: 'ticker'
[2025-04-24T21:15:44.055+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_prices_data_downloader_branching, task_id=branch_TATASTEEL.NS, execution_date=20250424T211540, start_date=20250424T211543, end_date=20250424T211544
[2025-04-24T21:15:44.068+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 227 for task branch_TATASTEEL.NS (prices_pipeline.<locals>.branch_condition() missing 1 required positional argument: 'ticker'; 4205)
[2025-04-24T21:15:44.083+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-24T21:15:44.112+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
