[2025-04-21T10:02:59.449+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prices_dag.save_to_excel manual__2025-04-21T10:01:50.704196+00:00 [queued]>
[2025-04-21T10:02:59.456+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prices_dag.save_to_excel manual__2025-04-21T10:01:50.704196+00:00 [queued]>
[2025-04-21T10:02:59.456+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-21T10:02:59.467+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_excel> on 2025-04-21 10:01:50.704196+00:00
[2025-04-21T10:02:59.474+0000] {standard_task_runner.py:60} INFO - Started process 1006 to run task
[2025-04-21T10:02:59.478+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prices_dag', 'save_to_excel', 'manual__2025-04-21T10:01:50.704196+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/prices_dag.py', '--cfg-path', '/tmp/tmp6m1o0jil']
[2025-04-21T10:02:59.480+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask save_to_excel
[2025-04-21T10:02:59.520+0000] {task_command.py:423} INFO - Running <TaskInstance: prices_dag.save_to_excel manual__2025-04-21T10:01:50.704196+00:00 [running]> on host 6e9dceb52ab5
[2025-04-21T10:02:59.591+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prices_dag' AIRFLOW_CTX_TASK_ID='save_to_excel' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T10:01:50.704196+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T10:01:50.704196+00:00'
[2025-04-21T10:02:59.603+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/prices_dag.py:72 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2025-04-21T10:02:59.812+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/prices_dag.py", line 79, in save_to_excel
    save_to_mongo(file_path)
  File "/opt/airflow/dags/prices_dag.py", line 97, in save_to_mongo
    MONGODB_COLLECTION.insert_one(file_doc)
AttributeError: 'str' object has no attribute 'insert_one'
[2025-04-21T10:02:59.820+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=prices_dag, task_id=save_to_excel, execution_date=20250421T100150, start_date=20250421T100259, end_date=20250421T100259
[2025-04-21T10:02:59.831+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task save_to_excel ('str' object has no attribute 'insert_one'; 1006)
[2025-04-21T10:02:59.849+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-21T10:02:59.864+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
